version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: spendsense
      POSTGRES_PASSWORD: spendsense
      POSTGRES_DB: spendsense
    ports:
      - "5432:5432"

  metabase:
    image: metabase/metabase:latest
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.7
    volumes:
      - ./dbt:/usr/app
    depends_on:
      - postgres
